### ISSUE TITLE
daytona container-registry feature explained

### ISSUE THREAD

**Issue by nkkko** [daytonaio/content#34]
### Content Type

None

### Article Description

Write article to present daytona container-registry feature. Use up to 2 screenshots, code snippets and sample repo (can be existing one) for which you will create project-config.

### Target Audience

individual dev

**Comment by nkkko** [comment]
@Niharika0104 any updates?

**Comment by Ekemini004** [comment]
@Niharika0104 , this bounty still open for an attempt ? C

**Comment by Niharika0104** [comment]
@Ekemini004 yes
