### ISSUE TITLE
Daytona Fly Provider

### ISSUE THREAD

**Issue by nkkko** [daytonaio/content#79]
### Content Type
Article

### Article Description
This article outlines the features and functionalities of the newly introduced Daytona Fly Provider. This provider allows Daytona to create workspace projects on Fly VMs known as Fly Machines. The main objective of this article is to explain how to set up and use the Fly Provider within Daytona, as well as to update the existing documentation to include these new features. Key points to cover include installation, configuration, and usage of the Fly Provider, as well as troubleshooting common issues.

### Target Audience
Developers and DevOps professionals who are currently using or are interested in using Daytona for managing and deploying workspaces. This includes individuals working with Fly.io infrastructure and those looking for alternative cloud-hosting providers.

### References/Resources
- [Daytona Docs - Configuration Providers](https://www.daytona.io/docs/configuration/providers/#officially-supported-providers)
- [Daytona.io Fly Provider Repository](https://github.com/daytonaio/daytona-provider-fly)
- [Daytona Releases - v0.25.2](https://github.com/daytonaio/daytona/releases/tag/v0.25.2)

### Special Instructions
Ensure that the article includes step-by-step instructions for setting up the Fly Provider, complete with command examples and screenshots where applicable. Also, include a section on common issues and troubleshooting tips. Mention the alpha release state of the Fly Provider and any known limitations or caveats.

**Comment by scshiv29-dev** [comment]
@nkkko  how do I link images ? I created a new folder /assets/articles/ and added images in it but I am not sure if they'll render.
